username-bypass: {}
banned-isps:
  - 'SECURED SERVERS LLC'
  - 'FDCservers.net'
  - 'SoftLayer Technologies Inc.'
  - 'ORG-VS46-RIPE'
  - 'NOC4Hosts Inc.'
  - 'AnchorFree Inc.'
  - 'Voxility'
  - 'Amazon Technologies Inc.'
  - 'Ace Data Centers, Inc.'
  - 'QuadraNet, Inc'
  - 'PlusServer'
  - 'TrueServer'
  - 'Rackspace'
  - 'OVH Hosting'
  - 'OVH SAS'
  - 'London Trust Media'
  - 'Hosting Services'
  - 'COS&CIE SAS'