name: BetterDNSBL
main: com.beastsmc.dnsbl.BetterDNSBL
version: 0.1
commands:
   dnsbl:
      usage: /dnsbl reload
      permission: beastsmc.admin
      permission-message: You do not have permission to use this command!